"""
Django settings for BCST_Sales_Tool project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
# APPEND_SLASH = False
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# pythonpath = r"C:/Users/MihirPawar/Desktop/Python Project BSW/Python Files1/ccv_tool//"
pythonpath = r"C:/python project/BCST_Sales_Tool//"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z#0b+a5oy2ib#40*%2^51&_+8k+)@()z+8z9%g0*_f36is0p+_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG=True


ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ['*']
# MESSAGE_LEVEL = message_constants.DEBUG

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_SSL_REDIRECT = False


PYTHONPATH="uploaded_data/transform_data/" #FOR LOCAL MACHINE USE THIS PATH
ORIGINAL_DATA="uploaded_data/original_data/" #FOR LOCAL MACHINE USE THIS PATH
TEMP_UPLOAD="uploaded_data/temp_data/" #FOR LOCAL MACHINE USE THIS PATH
SELLOUT_UPLOAD="uploaded_data/sellout/" #FOR SELLOUT USE THIS PATH
SKU_UPLOAD="uploaded_data/sku/" #FOR SKU USE THIS PATH
DOORS_UPLOAD="uploaded_data/doors/" #FOR DOORS USE THIS PATH
PYTHONPATH_JSON=r'uploaded_data\*.json' #FOR LOCAL MACHINE USE THIS PATH

MERGED_PYTHONPATH="merged_pythonpath/" #FOR LOCAL MACHINE USE THIS PATH
MERGED_PYTHONPATH_JSON=r'merged_pythonpath\*.json' #FOR LOCAL MACHINE USE THIS PATH
FINAL_CROSSTAB_OUTPUT="static/download_cross_table_excel/"

DATA_UPLOAD_MAX_MEMORY_SIZE=None

IMG_OUTPUT_PYTHONPATH = "static/chart_image_crosstab/"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main_dashboard',
    'login',
    'rest_framework',
    # 'Demo_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'login.middleware.PageVisitLogMiddleware',
]

ROOT_URLCONF = 'BCST_Sales_Tool.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BCST_Sales_Tool.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# server db connection string
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql', 
#         'NAME': 'bsw_tracker',
#         'USER': 'root',
#         'PASSWORD': 'BSWW432!',
#         'HOST': 'localhost',   
#         'PORT': '3306',
#     }    
# }

# local db connection string
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'bcs_sales_tracker',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',   
        'PORT': '3306',
    }    
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
############################# commented 04-04-2023 ###################################
# DATABASES = {
#      'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ccvtool',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': '127.0.0.1',
#         'PORT': '3306',
#         # 'OPTIONS': {'ssl': {'key':'C:/python project/Predictive Modelling/BaltimoreCyberTrustRoot.crt.pem'}}
#         # 'OPTIONS': {'ssl': {'key':'C:/Users/pravin.sonawane/Downloads/BaltimoreCyberTrustRoot.crt.pem'}}
#     }
# }
############################# commented 04-04-2023 ###################################

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
]
# STATIC_ROOT = os.path.join(BASE_DIR,'static')

# stage1 code start here
# STATIC_ROOT = os.path.join(BASE_DIR)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

############ DYNAMIC VARIABLES - COLUMN NAMES - 21-08-2024 ##############

############ DYNAMIC VARIABLES - COLUMN NAMES - 21-08-2024 ##############
